"""Generate an upgraded standalone graph viz (graph_pro.html) from graphify graph.json.

Non-destructive: leaves graphify-out/graph.html (regenerated by `graphify export html`)
untouched. Re-run after `graphify update` to refresh.

Upgrades over the default vis-network output:
- Color by file_type (code/document/concept/rationale/image) with toggle to community color
- Node size scaled by degree (god nodes pop)
- Edge confidence styling (EXTRACTED solid / INFERRED dashed) + hide-INFERRED filter
- Relation multi-filter chips
- Cross-community bridge score (distinct neighbor communities) + "Bridges" highlight
- Search, neighbor drill-down, source_file:line in info panel, physics freeze
"""
from __future__ import annotations

import json
import logging
from collections import Counter, defaultdict
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

OUT_DIR = Path(__file__).resolve().parent.parent / "graphify-out"
GRAPH_JSON = OUT_DIR / "graph.json"
OUT_HTML = OUT_DIR / "graph_pro.html"

TYPE_COLORS = {
    "code": "#4E79A7",
    "document": "#59A14F",
    "concept": "#E15759",
    "rationale": "#F28E2B",
    "image": "#B07AA1",
}
DEFAULT_COLOR = "#888888"
MIN_SIZE = 8.0
MAX_SIZE = 42.0


def community_color(cid: int) -> str:
    """Stable HSL color per community id."""
    hue = (int(cid) * 47) % 360
    return f"hsl({hue}, 55%, 58%)"


def scale_size(degree: int, max_deg: int) -> float:
    if max_deg <= 0:
        return MIN_SIZE
    import math

    t = math.log1p(degree) / math.log1p(max_deg)
    return round(MIN_SIZE + (MAX_SIZE - MIN_SIZE) * t, 1)


def build() -> None:
    if not GRAPH_JSON.exists():
        raise SystemExit(f"graph.json not found at {GRAPH_JSON} — run /graphify first")

    g = json.loads(GRAPH_JSON.read_text(encoding="utf-8"))
    raw_nodes = g.get("nodes", [])
    raw_links = g.get("links", [])
    hyperedges = g.get("hyperedges", [])

    # degree + cross-community bridge score
    degree: Counter = Counter()
    neighbor_comms: dict[str, set] = defaultdict(set)
    id2comm = {n["id"]: n.get("community") for n in raw_nodes}
    for l in raw_links:
        s, t = l["source"], l["target"]
        degree[s] += 1
        degree[t] += 1
        if id2comm.get(s) is not None and id2comm.get(t) is not None and id2comm[s] != id2comm[t]:
            neighbor_comms[s].add(id2comm[t])
            neighbor_comms[t].add(id2comm[s])
    max_deg = max(degree.values()) if degree else 1

    comm_labels = {str(k): v for k, v in (g.get("graph", {}).get("community_labels", {}) or {}).items()}
    # fall back to .graphify_labels.json if present
    labels_file = OUT_DIR / ".graphify_labels.json"
    if labels_file.exists():
        try:
            comm_labels.update(json.loads(labels_file.read_text(encoding="utf-8")))
        except Exception:
            pass

    nodes = []
    for n in raw_nodes:
        nid = n["id"]
        ft = n.get("file_type") or "code"
        deg = degree.get(nid, 0)
        bridges = len(neighbor_comms.get(nid, ()))
        cid = n.get("community")
        nodes.append(
            {
                "id": nid,
                "label": n.get("label") or nid,
                "ft": ft,
                "src": n.get("source_file") or "",
                "loc": n.get("source_location") or "",
                "origin": n.get("_origin") or "",
                "comm": cid,
                "commLabel": comm_labels.get(str(cid), f"Community {cid}"),
                "deg": deg,
                "bridges": bridges,
                "size": scale_size(deg, max_deg),
                "cType": TYPE_COLORS.get(ft, DEFAULT_COLOR),
                "cComm": community_color(cid) if cid is not None else DEFAULT_COLOR,
            }
        )

    edges = [
        {
            "from": l["source"],
            "to": l["target"],
            "rel": l.get("relation") or "",
            "conf": l.get("confidence") or "",
            "cs": l.get("confidence_score"),
            "src": l.get("source_file") or "",
        }
        for l in raw_links
    ]

    relations = sorted({e["rel"] for e in edges if e["rel"]})
    ft_counts = Counter(n["ft"] for n in nodes)

    payload = {
        "nodes": nodes,
        "edges": edges,
        "hyperedges": hyperedges,
        "relations": relations,
        "ftCounts": dict(ft_counts),
        "typeColors": TYPE_COLORS,
        "stats": {
            "nodes": len(nodes),
            "edges": len(edges),
            "communities": len({n["comm"] for n in nodes if n["comm"] is not None}),
            "hyperedges": len(hyperedges),
            "inferred": sum(1 for e in edges if e["conf"] == "INFERRED"),
        },
    }

    html = HTML_TEMPLATE.replace("__DATA__", json.dumps(payload, ensure_ascii=False))
    OUT_HTML.write_text(html, encoding="utf-8")
    logger.info("graph_pro.html written: %s", OUT_HTML)
    logger.info(
        "  %d nodes, %d edges, %d communities, %d INFERRED edges",
        payload["stats"]["nodes"],
        payload["stats"]["edges"],
        payload["stats"]["communities"],
        payload["stats"]["inferred"],
    )


HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>graphify pro — SCT_ONTOLOGY</title>
<script src="https://unpkg.com/vis-network@9.1.6/standalone/umd/vis-network.min.js"
        integrity="sha384-Ux6phic9PEHJ38YtrijhkzyJ8yQlH8i/+buBR8s3mAZOJrP1gwyvAcIYl3GWtpX1"
        crossorigin="anonymous"></script>
<style>
  :root{--bg:#0c0c16;--panel:#15152a;--panel2:#1d1d38;--line:#2a2a4e;--accent:#6ea8e0;--txt:#e6e6ef;--muted:#8a8aa8;}
  *{box-sizing:border-box;margin:0;padding:0;}
  body{background:var(--bg);color:var(--txt);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;display:flex;height:100vh;overflow:hidden;font-size:13px;}
  #graph{flex:1;position:relative;}
  #topbar{position:absolute;top:0;left:0;right:0;z-index:5;display:flex;gap:8px;align-items:center;padding:10px 14px;background:linear-gradient(180deg,rgba(12,12,22,.92),rgba(12,12,22,0));pointer-events:none;flex-wrap:wrap;}
  #topbar>*{pointer-events:auto;}
  .pill{background:var(--panel);border:1px solid var(--line);border-radius:20px;padding:5px 12px;font-size:12px;color:var(--muted);cursor:pointer;user-select:none;transition:.15s;}
  .pill:hover{border-color:var(--accent);color:var(--txt);}
  .pill.on{background:var(--accent);border-color:var(--accent);color:#0c0c16;font-weight:600;}
  .pill.rel{font-size:11px;padding:3px 9px;}
  #relbar{display:flex;gap:5px;flex-wrap:wrap;max-width:62vw;}
  #sidebar{width:320px;background:var(--panel);border-left:1px solid var(--line);display:flex;flex-direction:column;overflow:hidden;}
  .sec{padding:12px 14px;border-bottom:1px solid var(--line);}
  .sec h3{font-size:11px;color:var(--muted);margin-bottom:8px;text-transform:uppercase;letter-spacing:.06em;}
  #search{width:100%;background:var(--bg);border:1px solid #3a3a5e;color:var(--txt);padding:8px 10px;border-radius:6px;font-size:13px;outline:none;}
  #search:focus{border-color:var(--accent);}
  #search-results{max-height:160px;overflow-y:auto;margin-top:6px;display:none;}
  .si{padding:5px 7px;cursor:pointer;border-radius:4px;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
  .si:hover{background:var(--panel2);}
  .si .ftdot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;}
  #info .empty{color:#555;font-style:italic;}
  #info .field{margin-bottom:5px;line-height:1.5;}
  #info .field b{color:var(--txt);}
  #info .badge{display:inline-block;font-size:10px;padding:1px 7px;border-radius:10px;margin-right:4px;}
  #neighbors{max-height:200px;overflow-y:auto;margin-top:6px;flex:1;}
  .nl{display:block;padding:4px 7px;margin:2px 0;border-radius:4px;cursor:pointer;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;border-left:3px solid #333;}
  .nl:hover{background:var(--panel2);}
  .nl .rel{color:var(--muted);font-size:10px;}
  #legend{flex:1;overflow-y:auto;}
  .lg{display:flex;align-items:center;gap:8px;padding:4px 0;font-size:12px;}
  .lg .dot{width:12px;height:12px;border-radius:50%;flex-shrink:0;}
  .lg .ct{color:var(--muted);font-size:11px;margin-left:auto;}
  #stats{padding:9px 14px;border-top:1px solid var(--line);font-size:11px;color:var(--muted);}
  #bridges-list{max-height:200px;overflow-y:auto;}
  .br{display:flex;justify-content:space-between;gap:6px;padding:4px 7px;border-radius:4px;cursor:pointer;font-size:12px;}
  .br:hover{background:var(--panel2);}
  .br .b{color:#f2c14e;font-size:11px;flex-shrink:0;}
  #conf-wrap{display:flex;align-items:center;gap:8px;}
</style>
</head>
<body>
<div id="graph">
  <div id="topbar">
    <span class="pill on" id="t-color">색상: 파일타입</span>
    <span class="pill on" id="t-inf">INFERRED 표시</span>
    <span class="pill" id="t-bridge">🌉 Bridges 강조</span>
    <span class="pill" id="t-phys">물리엔진 ON</span>
    <span class="pill" id="t-fit">전체보기</span>
    <div id="relbar"></div>
  </div>
</div>
<div id="sidebar">
  <div class="sec"><h3>검색</h3><input id="search" placeholder="노드 검색…" autocomplete="off"><div id="search-results"></div></div>
  <div class="sec" style="min-height:150px;"><h3>선택 노드</h3><div id="info"><span class="empty">노드를 클릭하세요</span></div><div id="neighbors"></div></div>
  <div class="sec"><h3>Top Bridges (교차 커뮤니티)</h3><div id="bridges-list"></div></div>
  <div class="sec" id="legend-sec"><h3>파일 타입</h3><div id="legend"></div></div>
  <div id="stats"></div>
</div>
<script>
const DATA = __DATA__;
const TYPE_COLORS = DATA.typeColors;
const byId = Object.fromEntries(DATA.nodes.map(n=>[n.id,n]));
const adj = {};
DATA.nodes.forEach(n=>adj[n.id]=[]);
DATA.edges.forEach(e=>{ if(adj[e.from]&&adj[e.to]){adj[e.from].push({id:e.to,rel:e.rel,conf:e.conf}); adj[e.to].push({id:e.from,rel:e.rel,conf:e.conf});} });

let colorMode='type';        // 'type' | 'community'
let showInferred=true;
let bridgeMode=false;
let physics=true;
const relOff=new Set();      // hidden relations

const visNodes=new vis.DataSet(DATA.nodes.map(n=>nodeView(n)));
const visEdges=new vis.DataSet(DATA.edges.map((e,i)=>edgeView(e,i)));

function nodeColor(n){ return colorMode==='type'?n.cType:n.cComm; }
function nodeView(n){
  return {id:n.id,label:n.label,value:n.size,
    color:{background:nodeColor(n),border:'#0c0c16',highlight:{background:nodeColor(n),border:'#fff'}},
    font:{color:'#cfcfe6',size:n.deg>8?15:11,strokeWidth:3,strokeColor:'#0c0c16'},
    shape:n.ft==='code'?'dot':n.ft==='concept'?'diamond':n.ft==='rationale'?'triangle':n.ft==='image'?'square':'hexagon'};
}
function edgeView(e,i){
  const inf=e.conf==='INFERRED';
  return {id:'e'+i,from:e.from,to:e.to,rel:e.rel,conf:e.conf,
    dashes:inf?[4,4]:false,
    color:{color:inf?'#5a5a80':'#3a3a55',opacity:inf?0.5:0.7,highlight:'#6ea8e0'},
    width:inf?0.6:1,smooth:false,hidden:false};
}

const container=document.getElementById('graph');
const network=new vis.Network(container,{nodes:visNodes,edges:visEdges},{
  nodes:{scaling:{min:8,max:42}},
  edges:{arrows:{to:false}},
  physics:{enabled:true,solver:'forceAtlas2Based',
    forceAtlas2Based:{gravitationalConstant:-45,centralGravity:0.008,springLength:90,springConstant:0.05,avoidOverlap:0.4},
    // non-blocking: never run synchronous stabilization (it freezes the page + delays first paint on 1600+ nodes)
    stabilization:{enabled:false}},
  interaction:{hover:true,tooltipDelay:120,navigationButtons:false,keyboard:false},
  layout:{improvedLayout:false}
});
network.once('afterDrawing',()=>network.fit({animation:false}));
// auto-freeze physics after it settles so the layout stops drifting
setTimeout(()=>{ if(physics){physics=false;$('t-phys').classList.remove('on');$('t-phys').textContent='물리엔진 OFF';network.setOptions({physics:{enabled:false}});network.fit({animation:true});} },6000);

// ---- top bar ----
const $=id=>document.getElementById(id);
$('t-color').onclick=()=>{colorMode=colorMode==='type'?'community':'type';
  $('t-color').textContent='색상: '+(colorMode==='type'?'파일타입':'커뮤니티');
  $('t-color').classList.toggle('on',true);
  visNodes.update(DATA.nodes.map(n=>({id:n.id,color:{background:nodeColor(n),border:'#0c0c16',highlight:{background:nodeColor(n),border:'#fff'}}})));
  renderLegend();};
$('t-inf').onclick=()=>{showInferred=!showInferred;$('t-inf').classList.toggle('on',showInferred);applyEdgeFilter();};
$('t-bridge').onclick=()=>{bridgeMode=!bridgeMode;$('t-bridge').classList.toggle('on',bridgeMode);applyBridge();};
$('t-phys').onclick=()=>{physics=!physics;$('t-phys').classList.toggle('on',physics);$('t-phys').textContent='물리엔진 '+(physics?'ON':'OFF');network.setOptions({physics:{enabled:physics}});};
$('t-fit').onclick=()=>network.fit({animation:true});

// relation chips
const relbar=$('relbar');
DATA.relations.forEach(r=>{const c=document.createElement('span');c.className='pill rel on';c.textContent=r;
  c.onclick=()=>{if(relOff.has(r)){relOff.delete(r);c.classList.add('on');}else{relOff.add(r);c.classList.remove('on');}applyEdgeFilter();};
  relbar.appendChild(c);});

function applyEdgeFilter(){
  visEdges.update(DATA.edges.map((e,i)=>{
    const hide=(!showInferred&&e.conf==='INFERRED')||relOff.has(e.rel);
    return {id:'e'+i,hidden:hide};
  }));
}
function applyBridge(){
  visNodes.update(DATA.nodes.map(n=>{
    const dim=bridgeMode&&n.bridges<2;
    return {id:n.id,opacity:dim?0.18:1,
      borderWidth:bridgeMode&&n.bridges>=3?3:1,
      color:{background:nodeColor(n),border:bridgeMode&&n.bridges>=3?'#f2c14e':'#0c0c16',highlight:{background:nodeColor(n),border:'#fff'}}};
  }));
}

// ---- info panel ----
network.on('click',p=>{ if(p.nodes.length) selectNode(p.nodes[0]); });
function selectNode(id){
  const n=byId[id]; if(!n)return;
  network.selectNodes([id]); network.focus(id,{scale:1.15,animation:true});
  const loc=n.loc?(':'+n.loc):'';
  $('info').innerHTML=
    `<div class="field"><span class="badge" style="background:${n.cType};color:#0c0c16">${n.ft}</span>`+
    `<span class="badge" style="background:#2a2a4e;color:#cfcfe6">deg ${n.deg}</span>`+
    (n.bridges?`<span class="badge" style="background:#5a4a1e;color:#f2c14e">🌉 ${n.bridges}</span>`:'')+`</div>`+
    `<div class="field"><b>${esc(n.label)}</b></div>`+
    `<div class="field" style="color:var(--muted)">${esc(n.src)}${loc}</div>`+
    `<div class="field" style="color:var(--muted)">${esc(n.commLabel)}</div>`;
  const ns=document.getElementById('neighbors');
  const seen=new Set();const items=[];
  (adj[id]||[]).forEach(x=>{const k=x.id;if(seen.has(k))return;seen.add(k);const m=byId[k];if(!m)return;
    items.push(`<a class="nl" style="border-left-color:${m.cType}" data-id="${k}"><span class="rel">${x.rel}</span> ${esc(m.label)}</a>`);});
  ns.innerHTML=items.length?items.join(''):'<span class="empty">연결 없음</span>';
  ns.querySelectorAll('.nl').forEach(a=>a.onclick=()=>selectNode(a.dataset.id));
}
function esc(s){return (s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}

// ---- search ----
const sb=$('search'),sr=$('search-results');
sb.oninput=()=>{const q=sb.value.trim().toLowerCase();if(!q){sr.style.display='none';return;}
  const hits=DATA.nodes.filter(n=>n.label.toLowerCase().includes(q)||n.id.toLowerCase().includes(q)).slice(0,40);
  sr.innerHTML=hits.map(n=>`<div class="si" data-id="${n.id}"><span class="ftdot" style="background:${n.cType}"></span>${esc(n.label)} <span style="color:#555">deg ${n.deg}</span></div>`).join('');
  sr.style.display=hits.length?'block':'none';
  sr.querySelectorAll('.si').forEach(d=>d.onclick=()=>{selectNode(d.dataset.id);sr.style.display='none';sb.value=byId[d.dataset.id].label;});
};

// ---- legend (file types) ----
function renderLegend(){
  const wrap=$('legend');
  $('legend-sec').querySelector('h3').textContent=colorMode==='type'?'파일 타입':'커뮤니티 (상위)';
  if(colorMode==='type'){
    wrap.innerHTML=Object.entries(TYPE_COLORS).map(([t,c])=>
      `<div class="lg"><span class="dot" style="background:${c}"></span>${t}<span class="ct">${DATA.ftCounts[t]||0}</span></div>`).join('')+
      `<div class="lg" style="margin-top:6px;color:var(--muted)"><span class="dot" style="background:#888"></span>모양: ●code ◆concept ▲rationale ■image ⬡document</div>`;
  }else{
    const cc={}; DATA.nodes.forEach(n=>{cc[n.comm]=(cc[n.comm]||0)+1;});
    const top=Object.entries(cc).sort((a,b)=>b[1]-a[1]).slice(0,18);
    wrap.innerHTML=top.map(([cid,ct])=>{const lab=(DATA.nodes.find(n=>String(n.comm)===String(cid))||{}).commLabel||('C'+cid);
      return `<div class="lg"><span class="dot" style="background:hsl(${(cid*47)%360},55%,58%)"></span>${esc(lab)}<span class="ct">${ct}</span></div>`;}).join('');
  }
}

// ---- bridges list ----
function renderBridges(){
  const top=[...DATA.nodes].filter(n=>n.bridges>0).sort((a,b)=>b.bridges-a.bridges||b.deg-a.deg).slice(0,25);
  $('bridges-list').innerHTML=top.map(n=>
    `<div class="br" data-id="${n.id}"><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(n.label)}</span><span class="b">🌉${n.bridges} · d${n.deg}</span></div>`).join('');
  $('bridges-list').querySelectorAll('.br').forEach(d=>d.onclick=()=>selectNode(d.dataset.id));
}

$('stats').textContent=`${DATA.stats.nodes} nodes · ${DATA.stats.edges} edges · ${DATA.stats.communities} communities · ${DATA.stats.inferred} INFERRED · ${DATA.stats.hyperedges} hyperedges`;
renderLegend();renderBridges();
</script>
</body>
</html>"""

if __name__ == "__main__":
    build()
