"""Seed Cloudflare D1 with normalized Control Tower CSV datasets.

The source CSV files live in data/datasets/ and are generated by
scripts/build_logistics_dataset.py. This script creates chunked SQL files and
applies them through wrangler d1 execute so the same path works locally and
against the remote D1 database.
"""

from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parents[1]
DATASET_DIR = ROOT / "data" / "datasets"
MIGRATION = ROOT / "migrations" / "0004_control_tower_datasets.sql"


def sql_string(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text == "":
        return "NULL"
    return "'" + text.replace("'", "''") + "'"


def to_int(value: str) -> int | None:
    return int(value) if value != "" else None


def to_float(value: str) -> float | None:
    return float(value) if value != "" else None


def to_bool_int(value: str) -> int:
    return 1 if value.strip().lower() == "true" else 0


def text(value: str) -> str | None:
    return value if value != "" else None


Converter = Callable[[str], object]


@dataclass(frozen=True)
class ColumnMap:
    db: str
    csv: str | None
    convert: Converter = text
    default: object = None

    def value(self, row: dict[str, str]) -> object:
        if self.csv is None:
            return self.default
        return self.convert(row.get(self.csv, ""))


@dataclass(frozen=True)
class DatasetSpec:
    file_name: str
    table: str
    columns: list[ColumnMap]


DATASETS: list[DatasetSpec] = [
    DatasetSpec(
        "shipment_unit.csv",
        "shipment_unit",
        [
            ColumnMap("shipment_unit_id", "shipmentUnitId"),
            ColumnMap("source_line_id", "sourceLineId"),
            ColumnMap("vendor", "vendor"),
            ColumnMap("category", "category"),
            ColumnMap("po_no", "poNo"),
            ColumnMap("invoice_no", "invoiceNo"),
            ColumnMap("incoterms", "incoterms"),
            ColumnMap("declared_destination_set", "declaredDestinationSet"),
            ColumnMap("declared_destination_count", "declaredDestinationCount", to_int),
            ColumnMap("current_stage", "currentStage"),
            ColumnMap("current_location", "currentLocation"),
            ColumnMap("routing_pattern", "routingPattern"),
            ColumnMap("latest_receipt_dt", "latestReceiptDt"),
            ColumnMap("final_delivery_dt", "finalDeliveryDt"),
            ColumnMap("site_completion_rate", "siteCompletionRate", to_float),
            ColumnMap("missing_required_destination", "missingRequiredDestination"),
            ColumnMap("received_without_flag", "receivedWithoutFlag"),
        ],
    ),
    DatasetSpec(
        "milestone_event.csv",
        "milestone_event",
        [
            ColumnMap("id", "milestoneEventId"),
            ColumnMap("shipment_unit_id", "shipmentUnitId"),
            ColumnMap("milestone_code", "milestoneCode"),
            ColumnMap("planned_dt", None),
            ColumnMap("estimated_dt", None),
            ColumnMap("actual_dt", "occurredAt"),
            ColumnMap("evidence_doc_id", "sourceColumn"),
        ],
    ),
    DatasetSpec(
        "action_queue.csv",
        "action_queue",
        [
            ColumnMap("action_id", "actionId"),
            ColumnMap("shipment_unit_id", "shipmentUnitId"),
            ColumnMap("action_type", "actionType"),
            ColumnMap("owner_role", "ownerRole"),
            ColumnMap("target_location", "targetLocation"),
            ColumnMap("due_at", "dueAt"),
            ColumnMap("status", "status"),
            ColumnMap("reason_code", "reasonCode"),
        ],
    ),
    DatasetSpec(
        "destination_requirement.csv",
        "destination_requirement",
        [
            ColumnMap("requirement_id", "requirementId"),
            ColumnMap("shipment_unit_id", "shipmentUnitId"),
            ColumnMap("destination_code", "destinationCode"),
            ColumnMap("required_flag", "requiredFlag", to_bool_int),
            ColumnMap("source_column", "sourceColumn"),
            ColumnMap("source_line_id", "sourceLineId"),
            ColumnMap("validation_status", "validationStatus"),
            ColumnMap("reason_code", "reasonCode"),
        ],
    ),
    DatasetSpec(
        "receipt_event.csv",
        "receipt_event",
        [
            ColumnMap("receipt_event_id", "receiptEventId"),
            ColumnMap("shipment_unit_id", "shipmentUnitId"),
            ColumnMap("location_code", "locationCode"),
            ColumnMap("location_type", "locationType"),
            ColumnMap("actual_receipt_dt", "actualReceiptDt"),
            ColumnMap("source_column", "sourceColumn"),
            ColumnMap("source_line_id", "sourceLineId"),
            ColumnMap("matched_required_destination", "matchedRequiredDestination", to_bool_int),
            ColumnMap("validation_status", "validationStatus"),
            ColumnMap("reason_code", "reasonCode"),
        ],
    ),
    DatasetSpec(
        "validation_log.csv",
        "validation_log",
        [
            ColumnMap("validation_id", "validationId"),
            ColumnMap("shipment_unit_id", "shipmentUnitId"),
            ColumnMap("rule_id", "ruleId"),
            ColumnMap("severity", "severity"),
            ColumnMap("field", "field"),
            ColumnMap("value", "value"),
            ColumnMap("reason_code", "reasonCode"),
        ],
    ),
]


def read_rows(spec: DatasetSpec) -> list[dict[str, str]]:
    path = DATASET_DIR / spec.file_name
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def insert_statements(spec: DatasetSpec, rows: list[dict[str, str]], chunk_size: int) -> list[str]:
    columns = ", ".join(col.db for col in spec.columns)
    statements: list[str] = [f"DELETE FROM {spec.table};"]
    for index in range(0, len(rows), chunk_size):
        chunk = rows[index : index + chunk_size]
        values = []
        for row in chunk:
            values.append("(" + ", ".join(sql_string(col.value(row)) for col in spec.columns) + ")")
        statements.append(f"INSERT OR REPLACE INTO {spec.table} ({columns}) VALUES\n  " + ",\n  ".join(values) + ";")
    return statements


def run_wrangler(database: str, sql_file: Path, remote: bool) -> None:
    npx = shutil.which("npx.cmd") or shutil.which("npx")
    if not npx:
        raise RuntimeError("npx was not found on PATH. Install Node.js or run the script from a shell where npx is available.")
    cmd = [npx, "wrangler", "d1", "execute", database]
    if remote:
        cmd.append("--remote")
    cmd.extend(["--file", str(sql_file)])
    subprocess.run(cmd, cwd=ROOT, check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", default="hvdc-mcp-audit")
    parser.add_argument("--remote", action="store_true")
    parser.add_argument("--chunk-size", type=int, default=200)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    summary: list[tuple[str, int]] = []
    with tempfile.TemporaryDirectory(prefix="hvdc-d1-seed-") as tmp_dir_raw:
        tmp_dir = Path(tmp_dir_raw)
        migration_target = tmp_dir / MIGRATION.name
        migration_target.write_text(MIGRATION.read_text(encoding="utf-8"), encoding="utf-8")

        if not args.dry_run:
            run_wrangler(args.database, migration_target, args.remote)

        for spec in DATASETS:
            rows = read_rows(spec)
            statements = insert_statements(spec, rows, args.chunk_size)
            sql_path = tmp_dir / f"seed_{spec.table}.sql"
            sql_path.write_text("\n".join(statements) + "\n", encoding="utf-8")
            summary.append((spec.table, len(rows)))
            if not args.dry_run:
                run_wrangler(args.database, sql_path, args.remote)

    for table, count in summary:
        print(f"{table}: {count}")


if __name__ == "__main__":
    main()
