// Spec §5.8 (Phase 1 subset). Full list will be added in Phase 2.
export const ErrorCodes = [
  'NO_FILE',
  'UNSUPPORTED_FILE_TYPE',
  'UPLOAD_TOO_LARGE_REQUIRES_CLIENT_UPLOAD',
  'STORAGE_AUTH_FAILED',
  'JOB_NOT_FOUND',
  'INVALID_STATE',
  'PARSE_FAILED',
  'MCP_UNAVAILABLE',
  'VALIDATION_FAILED',
  'FORBIDDEN',
  'APPROVAL_REQUIRED',
  'EXPORT_FAILED',
  'EXPORT_REPLAY_DETECTED',
  'RERUN_FORBIDDEN',
  'ZERO_BLOCKED',
  'HUMAN_GATE_REQUIRED',
  'UNAUTHORIZED_APPROVAL',
  'APPROVAL_REQUIRED_FIELDS',
  'FX_POLICY_REQUIRED',
  'FX_POLICY_VALIDATION_FAILED',
  'PARSE_PDF_UNSUPPORTED',      // P3B EC-016 (415)
  'PARSE_PDF_LOW_CONFIDENCE'    // P3B/P3C (422) - low conf forces AMBER
] as const;
export type ErrorCode = typeof ErrorCodes[number];

const HTTP_BY_CODE: Record<ErrorCode, number> = {
  NO_FILE: 400,
  UNSUPPORTED_FILE_TYPE: 400,
  UPLOAD_TOO_LARGE_REQUIRES_CLIENT_UPLOAD: 413,
  STORAGE_AUTH_FAILED: 500,
  JOB_NOT_FOUND: 404,
  INVALID_STATE: 409,
  PARSE_FAILED: 422,
  MCP_UNAVAILABLE: 503,
  VALIDATION_FAILED: 422,
  FORBIDDEN: 403,
  APPROVAL_REQUIRED: 403,
  EXPORT_FAILED: 500,
  EXPORT_REPLAY_DETECTED: 200,
  RERUN_FORBIDDEN: 403,
  ZERO_BLOCKED: 403,
  HUMAN_GATE_REQUIRED: 403,
  UNAUTHORIZED_APPROVAL: 403,
  APPROVAL_REQUIRED_FIELDS: 400,
  FX_POLICY_REQUIRED: 403,
  FX_POLICY_VALIDATION_FAILED: 422,
  PARSE_PDF_UNSUPPORTED: 415,
  PARSE_PDF_LOW_CONFIDENCE: 422
};

export function httpForError(code: ErrorCode): number {
  return HTTP_BY_CODE[code];
}
